### ISSUE TITLE
Wallet journal two IS NOT RefType filters means no filters

### ISSUE THREAD

**Issue by SwimlanesOnline** [madcowfred/evething#30]
Reproduce:
1) Go to Wallet Journal
2) Set filter Corporation EQUAL to some corporation
3) Set filter RefType IS NOT some reftype (e.g. Bounty Prizes)
-- Everything will work until this point, it'll show corp journal entries sans Bounty Prizes --
4) Set another filter RefType IS NOT some other reftype (e.g. Medal Issued)
-- Now only the Corporation filter will still work and the two RefType filters are ineffective --

**Comment by Gillingham** [comment]
From the wallet page:
Filters of different types are queried using AND while filters of the same type are queried using OR, for example "Character == Bob, Item == Pants, Item == Hats" will turn into something like "WHERE Character == Bob AND (Item == Pants OR Item == Hats)".

The two RefType filters being ineffective are due to that, since you have two != statements for different things they will overlap each other and you end up with all RefTypes
