### ISSUE TITLE
Setting up workers

### ISSUE THREAD

**Issue by AMoo** [madcowfred/evething#7]
I've never used Celery so I'm having a few problems wit the workers.  A few lines outlining how to set the tasks up would be appreciated

**Comment by spapin** [comment]
api_updater is deprecated because it just doesn't scale very well - as more API keys are added, the run time of the process increases to the point where it has to do every check every time and it starts getting very behind. Celery workers are the replacement system, I need to add how to configure/use it to the docs but for a low volume development version:
- Add this stuff to local_settings.py:
  BROKER_URL = 'django://'
  INSTALLED_APPS = settings.INSTALLED_APPS + ('kombu.transport.django',)
- Run 'python manage.py syncdb'
- Start some worker processes: 'python manage.py celery worker -B -Q et_high,et_medium,et_low -c 2 -l info'

-B starts the 'beat' process (scheduled tasks), -Q blah specifies which queues, -c 2 is the number of workers, -l info enables massive logging spam. Don't leave that running for a long time if you have DEBUG enabled as it will eventually consume all available memory and explode :v:

If you plan to host a lot of keys, you'll need more workers and a real backend (Redis, an AMQP server, etc).Joepopo

**Comment by spapin** [comment]
Answer was from tazuki. he sent me this.

**Comment by AMoo** [comment]
I Googled a bit and installed Rabbitmq-Server and then created an init script which calls the single worker thread.  This seems to work for now but I'll have to look at using more than one worker when I put this live.

I haven't found what to add in the admin panel so that Django gives the info yet though.

**Comment by spapin** [comment]
What info?

**Comment by AMoo** [comment]
Site admin > Workers > Add.

Input box says hostname but everything I put in there is "OFFLINE".  No bioggie as I can view logs manually to see whats hapenning.
